create table
  public.global_inventory (
    id integer generated by default as identity,
    num_green_ml integer not null,
    gold integer not null,
    num_red_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;


  create table
  public.capacity (
    id integer generated by default as identity,
    ml_capacity integer null default 10000,
    potion_capacity integer null default 50,
    constraint capacity_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    cart_id integer generated by default as identity,
    potion_id integer not null default 0,
    quantity integer not null default 0,
    gold_cost integer not null default 0,
    constraint cart_items_pkey primary key (cart_id, potion_id),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id) on update restrict on delete restrict,
    constraint public_cart_items_potion_sku_fkey foreign key (potion_id) references potions (id) on update restrict on delete restrict
  ) tablespace pg_default;

  create table
  public.carts (
    cart_id integer generated by default as identity,
    total_potions_bought integer not null default 0,
    total_cost integer not null default 0,
    customer_class text null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_cart_id_key unique (cart_id)
  ) tablespace pg_default;

  create table
  public.potions (
    potion_sku text not null,
    green_ml integer null default 0,
    red_ml integer null default 0,
    blue_ml integer null default 0,
    dark_ml integer null default 0,
    price integer null,
    quantity integer null default 0,
    id integer not null,
    constraint potions_pkey primary key (id),
    constraint potions_id_key unique (id),
    constraint potions_blue_ml_check check ((blue_ml <= 100)),
    constraint potions_dark_ml_check check ((dark_ml <= 100)),
    constraint potions_green_ml_check check ((green_ml <= 100)),
    constraint potions_red_ml_check check ((red_ml <= 100))
  ) tablespace pg_default;

  create table
  public.processed (
    job_id integer generated by default as identity,
    type text not null,
    constraint processed_pkey primary key (
      job_id,
      type
    )
  ) tablespace pg_default;